package cn.com.sun.commons.dto;

import lombok.Data;

import java.io.Serializable;
import java.util.Date;

@Data
public class ManagerPerson implements Serializable {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_NUMBER
     *
     * @mbggenerated
     */
    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_TYPE
     *
     * @mbggenerated
     */
    private Integer idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_NAME
     *
     * @mbggenerated
     */
    private String idName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_MEDICIALCARE
     *
     * @mbggenerated
     */
    private String idMedicialcare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.SEX
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.AGE
     *
     * @mbggenerated
     */
    private Byte age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.CODE_AREA
     *
     * @mbggenerated
     */
    private String codeArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_HOUSER
     *
     * @mbggenerated
     */
    private String idHouser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_GROUP
     *
     * @mbggenerated
     */
    private Byte idGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.STATUS_CODE
     *
     * @mbggenerated
     */
    private Byte statusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.STATUS_WEDDING
     *
     * @mbggenerated
     */
    private Byte statusWedding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.EDUCATION
     *
     * @mbggenerated
     */
    private Byte education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.DATE_BORN
     *
     * @mbggenerated
     */
    private Date dateBorn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.DATE_DIE
     *
     * @mbggenerated
     */
    private Date dateDie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.TELEPHONE
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_WECHAT
     *
     * @mbggenerated
     */
    private String idWechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_QQ
     *
     * @mbggenerated
     */
    private String idQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ENTR_TIME
     *
     * @mbggenerated
     */
    private Date entrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ALTER_TIME
     *
     * @mbggenerated
     */
    private Date alterTime;
    private String id;

    public void setId(String id) {
        this.id = id;
    }
}