package cn.com.sun.commons.dto;

import java.util.Date;

public class ManagerPerson {

    private String idNumber;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_TYPE
     *
     * @mbggenerated
     */
    private Integer idType;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_NAME
     *
     * @mbggenerated
     */
    private String idName;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_MEDICIALCARE
     *
     * @mbggenerated
     */
    private String idMedicialcare;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.SEX
     *
     * @mbggenerated
     */
    private Byte sex;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.AGE
     *
     * @mbggenerated
     */
    private Byte age;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.CODE_AREA
     *
     * @mbggenerated
     */
    private String codeArea;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_HOUSER
     *
     * @mbggenerated
     */
    private String idHouser;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_GROUP
     *
     * @mbggenerated
     */
    private Byte idGroup;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.STATUS_CODE
     *
     * @mbggenerated
     */
    private Byte statusCode;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.STATUS_WEDDING
     *
     * @mbggenerated
     */
    private Byte statusWedding;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.EDUCATION
     *
     * @mbggenerated
     */
    private Byte education;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.DATE_BORN
     *
     * @mbggenerated
     */
    private Date dateBorn;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.DATE_DIE
     *
     * @mbggenerated
     */
    private Date dateDie;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.PHONE
     *
     * @mbggenerated
     */
    private String phone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.TELEPHONE
     *
     * @mbggenerated
     */
    private String telephone;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.EMAIL
     *
     * @mbggenerated
     */
    private String email;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_WECHAT
     *
     * @mbggenerated
     */
    private String idWechat;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ID_QQ
     *
     * @mbggenerated
     */
    private String idQq;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ENTR_TIME
     *
     * @mbggenerated
     */
    private Date entrTime;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column MANAGER_PERSON.ALTER_TIME
     *
     * @mbggenerated
     */
    private Date alterTime;
    private String id;


    public String getIdNumber() {
        return idNumber;
    }

    public void setIdNumber(String idNumber) {
        this.idNumber = idNumber;
    }

    public Integer getIdType() {
        return idType;
    }

    public void setIdType(Integer idType) {
        this.idType = idType;
    }

    public String getIdName() {
        return idName;
    }

    public void setIdName(String idName) {
        this.idName = idName;
    }

    public String getIdMedicialcare() {
        return idMedicialcare;
    }

    public void setIdMedicialcare(String idMedicialcare) {
        this.idMedicialcare = idMedicialcare;
    }

    public Byte getSex() {
        return sex;
    }

    public void setSex(Byte sex) {
        this.sex = sex;
    }

    public Byte getAge() {
        return age;
    }

    public void setAge(Byte age) {
        this.age = age;
    }

    public String getCodeArea() {
        return codeArea;
    }

    public void setCodeArea(String codeArea) {
        this.codeArea = codeArea;
    }

    public String getIdHouser() {
        return idHouser;
    }

    public void setIdHouser(String idHouser) {
        this.idHouser = idHouser;
    }

    public Byte getIdGroup() {
        return idGroup;
    }

    public void setIdGroup(Byte idGroup) {
        this.idGroup = idGroup;
    }

    public Byte getStatusCode() {
        return statusCode;
    }

    public void setStatusCode(Byte statusCode) {
        this.statusCode = statusCode;
    }

    public Byte getStatusWedding() {
        return statusWedding;
    }

    public void setStatusWedding(Byte statusWedding) {
        this.statusWedding = statusWedding;
    }

    public Byte getEducation() {
        return education;
    }

    public void setEducation(Byte education) {
        this.education = education;
    }

    public Date getDateBorn() {
        return dateBorn;
    }

    public void setDateBorn(Date dateBorn) {
        this.dateBorn = dateBorn;
    }

    public Date getDateDie() {
        return dateDie;
    }

    public void setDateDie(Date dateDie) {
        this.dateDie = dateDie;
    }

    public String getPhone() {
        return phone;
    }

    public void setPhone(String phone) {
        this.phone = phone;
    }

    public String getTelephone() {
        return telephone;
    }

    public void setTelephone(String telephone) {
        this.telephone = telephone;
    }

    public String getEmail() {
        return email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    public String getIdWechat() {
        return idWechat;
    }

    public void setIdWechat(String idWechat) {
        this.idWechat = idWechat;
    }

    public String getIdQq() {
        return idQq;
    }

    public void setIdQq(String idQq) {
        this.idQq = idQq;
    }

    public Date getEntrTime() {
        return entrTime;
    }

    public void setEntrTime(Date entrTime) {
        this.entrTime = entrTime;
    }

    public Date getAlterTime() {
        return alterTime;
    }

    public void setAlterTime(Date alterTime) {
        this.alterTime = alterTime;
    }

    public String getId() {
        return id;
    }

    public void setId(String id) {
        this.id = id;
    }
}