package cn.com.sun.mapper.clinic;

import cn.com.sun.commons.dto.ManagerPerson;

public interface IManagerPersonMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MANAGER_PERSON
     *
     * @mbggenerated
     */
    int insert(ManagerPerson record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table MANAGER_PERSON
     *
     * @mbggenerated
     */
    int insertSelective(ManagerPerson record);


    ManagerPerson queryByIDNumber(String id);
}